name: Build and test

on:
  push:
    branches: ['workflwo']
  pull_request:
    branches: ['workflwo']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
